version: '3.5'

services:

  yesplz-frontend:
    container_name: yesplz-frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '80:80'
    network_mode: "host"
    volumes:
       - type: bind
         source: /home/sjcho/yesplz/data/ns_woman_top/archive
         target: /srv/www/imgs
         readonly: true

